# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod "OAuthSwift", "~> 0.4.6"
pod 'Alamofire', '~> 3.0'
